[package]
name = "changepoint"
version = "0.1.0"
authors = ["Tyler Richie <TylerRichie@github.com>"]

[dependencies]
num = "0.1"
error-chain = "0.11"
rand = "0.3"
mersenne_twister = "1.1"
rayon = "0.8"